---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'false'
  name: hello-world-app-release-plan
  namespace: user-ns2
spec:
  application: hello-world-app
  target: managed-ns2
  tenantPipeline:
    serviceAccountName: tenant-service-account
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/seanconroy2021/konflux-release-example.git
        - name: revision
          value: main
        - name: pathInRepo
          value: pipelines/tenant-pipeline.yaml
    params:
      - name: motd
        value: "This is an example motd for a tenant"
  finalPipeline:
    serviceAccountName: final-service-account
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/konflux-ci/community-catalog.git
        - name: revision
          value: a5e45c62d8a5651b6449db94d5da22d79dba8d05
        - name: pathInRepo
          value: pipelines/notify-slack-on-failure/notify-slack-on-failure.yaml
    params:
      - name: secretName
        value: slack-webhook-secret
      - name: secretKeyName
        value: webhook-url
